//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Boletos
    {
        public int ID { get; set; }
        public int IDPasajero { get; set; }
        public int IDServicio { get; set; }
        public int IDComprobante { get; set; }
        public float Precio { get; set; }
    
        public virtual Comprobante Comprobante { get; set; }
        public virtual pasajero pasajero { get; set; }
        public virtual Servicio Servicio { get; set; }
    }
}
