//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cliente()
        {
            this.Comprobante = new HashSet<Comprobante>();
            this.Recervaciones = new HashSet<Recervaciones>();
        }
    
        public int ID { get; set; }
        public string Nombres { get; set; }
        public string Apellido { get; set; }
        public string DNI { get; set; }
        public string Ruc { get; set; }
        public string Correo { get; set; }
        public int Celular { get; set; }
        public Nullable<System.DateTime> nacimiento { get; set; }
        public string Tipo { get; set; }
        public string Direccion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comprobante> Comprobante { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Recervaciones> Recervaciones { get; set; }
    }
}
