//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cronograma_viajes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cronograma_viajes()
        {
            this.Recervaciones = new HashSet<Recervaciones>();
            this.Servicio = new HashSet<Servicio>();
        }
    
        public int ID { get; set; }
        public string Placa { get; set; }
        public int IDRuta { get; set; }
        public string IDusuario { get; set; }
        public System.DateTime Fecha_salida { get; set; }
    
        public virtual Buses Buses { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Ruta Ruta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Recervaciones> Recervaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Servicio> Servicio { get; set; }
    }
}
