//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recervaciones
    {
        public int ID { get; set; }
        public int IDCronograma { get; set; }
        public int IDCliente { get; set; }
        public System.DateTime Fecha_limite { get; set; }
        public string Estado { get; set; }
        public int Cantidad { get; set; }
        public System.DateTime Fecha_recerva { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Cronograma_viajes Cronograma_viajes { get; set; }
    }
}
