//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ruta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ruta()
        {
            this.Cronograma_viajes = new HashSet<Cronograma_viajes>();
        }
    
        public int ID { get; set; }
        public int IDOrigen { get; set; }
        public int IDDestino { get; set; }
        public string Nombre { get; set; }
        public System.TimeSpan Demora { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cronograma_viajes> Cronograma_viajes { get; set; }
        public virtual Lugar Lugar { get; set; }
        public virtual Lugar Lugar1 { get; set; }
    }
}
