//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidad
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class sistemaviajesContext : DbContext
    {
        public sistemaviajesContext()
            : base("name=sistemaviajesContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Boletos> Boletos { get; set; }
        public virtual DbSet<Buses> Buses { get; set; }
        public virtual DbSet<Cargo> Cargo { get; set; }
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<Comprobante> Comprobante { get; set; }
        public virtual DbSet<Cronograma_viajes> Cronograma_viajes { get; set; }
        public virtual DbSet<Empleado> Empleado { get; set; }
        public virtual DbSet<Lugar> Lugar { get; set; }
        public virtual DbSet<ModeloBus> ModeloBus { get; set; }
        public virtual DbSet<pasajero> pasajero { get; set; }
        public virtual DbSet<Recervaciones> Recervaciones { get; set; }
        public virtual DbSet<Ruta> Ruta { get; set; }
        public virtual DbSet<Servicio> Servicio { get; set; }
        public virtual DbSet<Turnos_definidos> Turnos_definidos { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
